ChipTest: PongGameMain.cpp
	g++ -g -Wall  -I../include -I../../../ChipmunkLibrary/Chipmunk-7.0.0/include/chipmunk  PongGameMain.cpp -L../include -lchipmunk -lpthread -static


babyLinux: PongGamemain.cpp
	g++ -g -Wall  -I../include -I../../../ChipmunkLibrary/Chipmunk-7.0.0/include/chipmunk  PongGameMain.cpp -L. -lchipmunk -lpthread -static
